name: Deploy Site
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.102' # SDK Version to use.
    - run: dotnet run -- deploy
      working-directory: MySite
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
